// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5XJa6wtkn-NveROAemcV9qDe4BTZilQ',
    appId: '1:764233134042:web:f41e4938be98d3f57f9ae3',
    messagingSenderId: '764233134042',
    projectId: 'movie-1d323',
    authDomain: 'movie-1d323.firebaseapp.com',
    storageBucket: 'movie-1d323.appspot.com',
    measurementId: 'G-5M3EQKV6QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLOYUHfq0bX5xVlfJgvUUJms4FDZEirRs',
    appId: '1:764233134042:android:f9c9a2dc91b9ca6c7f9ae3',
    messagingSenderId: '764233134042',
    projectId: 'movie-1d323',
    storageBucket: 'movie-1d323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLSpfpPseBxUv8yP7rYLYA0LLIaFIM3I',
    appId: '1:764233134042:ios:82b202462d1f57457f9ae3',
    messagingSenderId: '764233134042',
    projectId: 'movie-1d323',
    storageBucket: 'movie-1d323.appspot.com',
    iosBundleId: 'com.example.movieLib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLSpfpPseBxUv8yP7rYLYA0LLIaFIM3I',
    appId: '1:764233134042:ios:82b202462d1f57457f9ae3',
    messagingSenderId: '764233134042',
    projectId: 'movie-1d323',
    storageBucket: 'movie-1d323.appspot.com',
    iosBundleId: 'com.example.movieLib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv5XJa6wtkn-NveROAemcV9qDe4BTZilQ',
    appId: '1:764233134042:web:6c9d319fffdf8e677f9ae3',
    messagingSenderId: '764233134042',
    projectId: 'movie-1d323',
    authDomain: 'movie-1d323.firebaseapp.com',
    storageBucket: 'movie-1d323.appspot.com',
    measurementId: 'G-KDWM3Q5LE0',
  );
}
